const TIPES = [
  { id: "1",      label: "Semua" },
  { id: "2",       label: "Jadwal" },
  { id: "3", label: "Kerjaan" },
  { id: "4",      label: "Produktivitas" },
  { id: "5",    label: "Lainnya" },
];

const SITES = [
  { nama: "Naha's",
    url: "https://nafyu.notion.site/naha",
    tipe: "2",
    tag: "Naha Activities" },
  { nama: "Yuliana's",
    url: "https://nafyu.notion.site/yuliana",
    tipe: "2",
    tag: "Yuliana Activities" },
  { nama: "Nafyu",
    url: "https://nahafinance.vercel.app",
    tipe: "3",
    tag: "Finansial Tabungan" },
  { nama: "Naha's",
    url: "https://nafyu.notion.site/naha",
    tipe: "2",
    tag: "Naha Activities" },
  { nama: "Yuliana's",
    url: "https://nafyu.notion.site/yuliana",
    tipe: "2",
    tag: "Yuliana Activities" },
  { nama: "Nafyu",
    url: "https://nahafinance.vercel.app",
    tipe: "3",
    tag: "Finansial Tabungan" },
  { nama: "Naha's",
    url: "https://nafyu.notion.site/naha",
    tipe: "2",
    tag: "Naha Activities" },
  { nama: "Yuliana's",
    url: "https://nafyu.notion.site/yuliana",
    tipe: "2",
    tag: "Yuliana Activities" },
  { nama: "Nafyu",
    url: "https://nahafinance.vercel.app",
    tipe: "3",
    tag: "Finansial Tabungan" },
];